// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjjcgeswznakhhrqkkny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqamNnZXN3em5ha2hocnFra255Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5Mjg5NjMsImV4cCI6MjA1OTUwNDk2M30.zTvKKf7hOm26qjrHwOpawzNYnfOw-mJph4IuvoglJmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);